/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package nl.frankprins.ssms;

public final class R {
    public static final class array {
        public static final int boxes_array=0x7f040000;
    }
    public static final class attr {
    }
    public static final class id {
        public static final int bottomtext=0x7f050001;
        public static final int boxname=0x7f050005;
        public static final int entry=0x7f050003;
        public static final int label=0x7f050002;
        public static final int num_total=0x7f050006;
        public static final int select=0x7f050004;
        public static final int toptext=0x7f050000;
    }
    public static final class layout {
        public static final int box=0x7f020000;
        public static final int listrow=0x7f020001;
        public static final int new_sms_form=0x7f020002;
        public static final int smsbox_row=0x7f020003;
        public static final int smsboxes=0x7f020004;
    }
    public static final class string {
        public static final int app_name=0x7f030000;
        public static final int main_no_items=0x7f030002;
        public static final int messageListNamePrefixFrom=0x7f030003;
        public static final int messageListNamePrefixTo=0x7f030004;
        public static final int new_sms_button=0x7f030001;
    }
}
